sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -f -t vedangparasnis/dev Dockerfile.dev .

script:
  - docker run -e CI=true vedangparasnis/dev npm run test -- --coverage
