sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t <docker_id>/dev -f Dockerfile.dev .

script:
  - docker run -e CI=true <docker_id>/dev npm run test -- --coverage
