sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t vedangparasnis/dev -f Dockerfile.dev .

script:
  - docker run -e CI=true vedangparasnis/dev npm run test -- --coverage
